version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - kafka
  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - kafka
  notification-service:
    build: ./notification-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
